### ISSUE TITLE
Add locations

### ISSUE THREAD

**Issue by LeonorLunatech** [lunatech-labs/lunatech-lunch-planner#99]
# Description
The user should be able to define where a 'scheduled meal' is going to happen.
When creating an new 'scheduled meal' the user should see a dropdown with just two options:
- Amsterdam
- Rotterdam

The selection must be mandatory.

# Users
- Admin

=================================================================

Lunatech is growing and lunch has to be organised for more than one office on Fridays.
The current version does not have the notion off a location for the planned meals.

For admin users, add the possibility to add / modify locations.

The option to delete can also be added, but at least add a confirmation dialog to it.

**Comment by Shermans2806** [comment]
A third selection which should be mandotory is 'no'. So everyone must choose either Rotterdam, Amsterdam or No.

**Comment by pepite** [comment]
There is a super simple way to deal with that. Deploy two apps. That's way better than coding extra things and locking in the app. For ex it makes no sense at all to have add Paris or niort as location, because rules are different. It probably will be the same between rotterdam or Amsterdam. For ex we might decide the Friday is Wed in Amsterdam or other things. If you couple the app to two location it will become harder for location to be independent.

**Comment by pepite** [comment]
For me we need to close this issue. I think what we need is an easy way and common way to report which is something really différent issue. people are not going to go one week to one office and the next one to another. Punctually they will be exchanges, but that will stay exceptional.
